// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ExperienceForm(method string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if method == "POST" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/experience/\" hx-swap=\"outerHTML\"><div id=\"name\"><label for=\"name\">Employer Name:</label> <input type=\"text\" name=\"name\" required></div><div id=\"role\"><label for=\"name\">Role:</label> <input type=\"text\" name=\"role\" required></div><div id=\"start\"><label for=\"start\">Start date:</label> <input type=\"month\" name=\"start\" required></div><div id=\"finish\"><label for=\"finish\">Finish date:</label> <input type=\"month\" name=\"finish\" required></div><div id=\"current\"><label for=\"current\">Current employer?:</label> <input hx-on:change=\"const finish = document.getElementById(&#39;finish&#39;); finish.style.display = this.checked ? &#39;none&#39; : &#39;block&#39;; finish.querySelector(&#39;input&#39;).required = !this.checked;\" type=\"checkbox\" name=\"current\"></div><div id=\"responsibilities\"><label for=\"responsibilities\">Responsibilities:</label> <textarea required hx-validate=\"true\" type=\"checkbox\" name=\"responsibilities\"></textarea></div><button type=\"submit\"><span>Submit</span></button> <span id=\"response\"></span></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if method == "GET" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/experience/\" hx-swap=\"outerHTML\"><div id=\"name\"><label for=\"name\">Employer Name:</label> <input type=\"text\" name=\"name\" required disabled></div><div id=\"role\"><label for=\"name\">Role:</label> <input type=\"text\" name=\"role\" required disabled></div><div id=\"start\"><label for=\"start\">Start date:</label> <input type=\"month\" name=\"start\" required disabled></div><div id=\"finish\"><label for=\"finish\">Finish date:</label> <input type=\"month\" name=\"finish\" required disabled></div><div id=\"current\"><label for=\"current\">Current employer?:</label> <input hx-on:change=\"const finish = document.getElementById(&#39;finish&#39;); finish.style.display = this.checked ? &#39;none&#39; : &#39;block&#39;; finish.querySelector(&#39;input&#39;).required = !this.checked;\" type=\"checkbox\" name=\"current\" disabled></div><div id=\"responsibilities\"><label for=\"responsibilities\">Responsibilities:</label> <textarea required hx-validate=\"true\" type=\"checkbox\" name=\"responsibilities\" disabled></textarea></div><button type=\"submit\" disabled><span>Submit</span></button> <span id=\"response\"></span></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
